# Generated by Django 5.2.7 on 2025-11-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecertificat',
            name='type_certificat',
            field=models.CharField(choices=[('naissance', 'Certificat de naissance'), ('mariage', 'Certificat de mariage'), ('deces', 'Certificat de décès'), ('residence', 'Certificat de résidence')], default='naissance', max_length=20),
        ),
    ]
