# Generated by Django 5.2.7 on 2025-11-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie_app', '0002_demandecertificat_type_certificat'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecertificat',
            name='annee_declaration',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='demandecertificat',
            name='numero_registre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
