# Generated by Django 5.2.7 on 2025-11-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie_app', '0003_demandecertificat_annee_declaration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandecertificat',
            options={},
        ),
        migrations.AddField(
            model_name='demandecertificat',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandecertificat',
            name='fichier_certificat',
            field=models.FileField(blank=True, null=True, upload_to='certificats/'),
        ),
        migrations.AddField(
            model_name='demandecertificat',
            name='numero_verification',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='demandecertificat',
            name='type_certificat',
            field=models.CharField(choices=[('naissance', 'Certificat de naissance'), ('mariage', 'Certificat de mariage'), ('deces', 'Certificat de décès'), ('residence', 'Certificat de résidence')], max_length=20),
        ),
    ]
