# Generated by Django 5.2.7 on 2025-11-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie_app', '0004_alter_demandecertificat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandecertificat',
            options={'verbose_name': 'Demande de Certificat', 'verbose_name_plural': 'Demandes de Certificat'},
        ),
        migrations.RemoveField(
            model_name='demandecertificat',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='demandecertificat',
            name='fichier_certificat',
        ),
        migrations.RemoveField(
            model_name='demandecertificat',
            name='numero_verification',
        ),
        migrations.AlterField(
            model_name='demandecertificat',
            name='type_certificat',
            field=models.CharField(choices=[('naissance', 'Certificat de naissance'), ('mariage', 'Certificat de mariage'), ('deces', 'Certificat de décès'), ('residence', 'Certificat de résidence')], default='naissance', max_length=20),
        ),
    ]
