# Generated by Django 5.1.6 on 2025-12-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie_app', '0005_alter_demandecertificat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandecertificat',
            options={},
        ),
        migrations.AlterField(
            model_name='demandecertificat',
            name='type_certificat',
            field=models.CharField(choices=[('naissance', 'Certificat de naissance'), ('mariage', 'Certificat de mariage'), ('deces', 'Certificat de décès'), ('residence', 'Certificat de résidence')], max_length=20),
        ),
    ]
