# Generated by Django 5.1.6 on 2025-12-01 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie_app', '0006_alter_demandecertificat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandecertificat',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Demande de Certificat', 'verbose_name_plural': 'Demandes de Certificat'},
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('methode', models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('MANUEL', 'Manuel (Mairie)')], default='WAVE', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EFFECTUE', 'Effectué'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='mairie_app.demandecertificat')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
