# Generated by Django 5.1.6 on 2025-12-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mairie_app', '0007_alter_demandecertificat_options_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='paydounya_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('PAYDOUNYA', 'Paydounya'), ('MANUEL', 'Manuel (Mairie)')], default='PAYDOUNYA', max_length=20),
        ),
    ]
